### ISSUE TITLE
Full or relative path for baseline image directory

### ISSUE THREAD

**Issue by MininAS** [jz-jess/RobotEyes#88] opened 2021-04-06 09:16 UTC
**Describe the bug**
What can we set like path for baseline image directory? Should it be full or relative path?
With full path a test finishes correctly.
```
*** Settings ***
Documentation     Documentation

Library           SeleniumLibrary
Library           RobotEyes

Suite Setup       Suite Setup
Suite Teardown    Close All Browsers
Force tags        google_logo

*** Variables ***
${IMAGES_DIR}     ${OUTPUT_DIR}${/}visual_images_original

*** Test cases ***
Google Logo Should Not Be Changed
    Open Eyes      SeleniumLibrary    tolerance=5
    Wait Until Element Is Visible     css:.k1zIA.rSk4se
    Capture Element                   css:.k1zIA.rSk4se    name=image
    Compare Images
    [Teardown]    No Operation

*** Keywords ***
Suite Setup
    Open Browser    https://www.google.com/    chrome
```

Console output =>
![image](https://user-images.githubusercontent.com/48047242/113679304-4cbccf80-96c8-11eb-8c77-b5ca1b57e18e.png)

But if we pointed relative path 
```
*** Variables ***
${IMAGES_DIR}     visual_images_original
```

Console output =>
![image](https://user-images.githubusercontent.com/48047242/113679530-88579980-96c8-11eb-8fd9-de0cc6b52046.png)

It is not blocker for testing localy, but it seems it affects to visual report at Jenkins automation server.
We need to publish visual report results to artifactory and report contains broken link to base line image.
An actual and diff links are correct.
I assume that this is related that we set the baseline image directory path like full.

**Comment by jz-jess** [comment] 2021-04-06 10:35
@MininAS Relative Baseline path is supported. From the error log it looks like the failure occurs where it expects the output directory to exist. A condition above the assert statement checks for the existence of baseline folder. Seems like that's working fine.
Is your baseline folder within the output folder? And are you passing absolute path to the output directory?

**Comment by MininAS** [comment] 2021-04-06 12:03
Yep, baseline folder `${OUTPUT_DIR}${/}visual_images_original` is in output folder.

**Comment by MininAS** [comment] 2021-04-06 12:06
> And are you passing absolute path to the output directory?
Yep. In this case OUTPUT_DIR = d:\robot-test-asset

**Comment by jz-jess** [comment] 2021-04-06 12:14
@MininAS Is this a separate location from where your tests are running?

**Comment by MininAS** [comment] 2021-04-06 12:17
the same


report_generation.py =>
```
import os
import xml.etree.ElementTree as ET
from time import sleep

from .constants import IMAGE_EXTENSIONS

def generate_report(baseline_folder, results_folder, actual_folder=None):
    sleep(1)
    img_path = os.path.join(results_folder, 'visual_images')
    report_path = os.path.join(results_folder, 'output.xml')
    relative_baseline_folder_path = relative_path(baseline_folder, results_folder.replace(os.getcwd(), ''))
    relative_actual_folder_path = relative_path(actual_folder, results_folder.replace(os.getcwd(), '')) if actual_folder else ''
```
    baseline_folder = "visual_images_original"
    results_folder = "D:\robot-test-asset"
so =>
    `results_folder.replace(os.getcwd(), '')` returns an empty because `os.getcwd()` = "D:\robot-test-asset"
then `relative_path` method gets the empty the second attribute and go to exception

**Comment by jz-jess** [comment] 2021-04-06 12:19
@MininAS Understood. The code is breaking when results are stored in the root itself. I'll fix this

**Comment by MininAS** [comment] 2021-04-06 12:22
Thank you!!! I'm looking forward to it. :)

**Comment by jz-jess** [comment] 2021-04-06 13:03
Hi @MininAS, I have pushed a fix in v1.5.7. Can you please upgrade and check if your issue gets resolved?

**Comment by MininAS** [comment] 2021-04-07 10:15
Big thanks!!! Works good locally and in automation Jenkins too.

**Closed** 2021-04-07 10:24 UTC

**Comment by Wutsarawuthiveground** [comment] 2021-11-05 09:55
Hello @MininAS 

          Could you please share the command to start your test?
so I had facing issue error >> 'please provide image baseline directory'

My command is >>  robot -d regression -v image_dir:out1 .\robot-test\..

**Comment by MininAS** [comment] 2021-11-09 07:34
Hi! Your varible name is image_dir and should be images_dir.
