### ISSUE TITLE
Result output in a non-root directory (

### ISSUE THREAD

**Issue by 12jakubpavel** [jz-jess/RobotEyes#75] opened 2020-09-07 19:02 UTC
**Describe the bug**
If I run this command: **_robot -d ./../DCS/results -v
images_dir:./../DCS/results/visual_images/baseline --test "PDF Visual
Overflow" ./../DCS_**  generate_report fail

If I run this command: **_robot -d results -v
images_dir:./../DCS/results/visual_images/baseline --test "PDF Visual
Overflow" ./../DCS_**  generate_report pass

**Screenshots**
**_robot -d ./../LTSA/DCS/results -v images_dir:./../LTSA/DCS/results/visual_images/baseline --test "Verify Strata Property Act Filing PDF Visual Overflow" ./../LTSA/DCS_**
![image](https://user-images.githubusercontent.com/37021143/92412503-61de7980-f14c-11ea-9844-d99a3f326bb2.png)

**_robot -d results -v images_dir:./../LTSA/DCS/results/visual_images/baseline --test "Verify Strata Property Act Filing PDF Visual Overflow" ./../LTSA/DCS_**
![image](https://user-images.githubusercontent.com/37021143/92412565-a23df780-f14c-11ea-9c79-24e689e7835f.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 1.5.1

**Comment by Twista** [comment] 2020-09-09 10:17
Hello, I have same problem. 

It seems that the issue is in this line

https://github.com/jz-jess/RobotEyes/blob/master/RobotEyes/__init__.py#L246

when absolute windows path (e.g. `C:\Results`) is provided, the first letter is stripped and therefore report_path is set to \Results - which doesn't exist

**Comment by jz-jess** [comment] 2020-09-09 14:44
Fix released in 1.5.2

**Closed by jz-jess** 2020-09-09 14:44 UTC
