### ISSUE TITLE
Haven't been succesful with Capture Element (SL lib)

### ISSUE THREAD

**Issue by leeuwe** [jz-jess/RobotEyes#79] opened 2020-11-12 13:50 UTC
**Describe the bug**
When using Capture Element, it still captures the whole screen. I've tried everything i could think of, but it just isn't working. 

**To Reproduce**
Open Eyes    lib=SeleniumLibrary    tolerance=10
[some navigate selenium steps]
Capture Element  id=map
Result:
![img1](https://user-images.githubusercontent.com/66635066/98947941-19e62500-24f6-11eb-9527-a8705dc1ed7a.png)

**Expected behavior**
I'm expecting to only capture the map on the right. Locator correct and verified, as works with seleniumlibrary.Capture Element Screenshot keyword

**Screenshots**
added

**Desktop (please complete the following information):**
 - OS: 
 - Browser Chrome 
 - Version robotframework-eyes                1.5.2

**Additional context**
Public URL: https://viewer.dso.kadaster.nl/zoeken

**Comment by jz-jess** [comment] 2020-11-12 13:54
@leeuwe Apparently I ended up breaking multiple things in the last release. I just fixed them and released in 1.5.3. Could you please upgrade and try?

**Comment by jz-jess** [comment] 2020-11-13 07:29
Closing this. Please reopen if the issue is still happening

**Closed by jz-jess** 2020-11-13 07:29 UTC

**Comment by leeuwe** [comment] 2020-11-13 09:05
@jz-jess Thanks for the awesomely quick response and fix. All works smooth and quick!
